[tool.poetry]
name = "pyaffine"
version = "0.1.7"
description = ""
authors = ["davidshivaji <davidshivaji@gmail.com>"]

[tool.poetry.scripts]
affine = "pyaffine.affine:go"

# [tool.poetry.scripts]
# poetry = 'poetry.console:run'

[tool.poetry.dependencies]
python = "^3.9"
python-datamuse = "1.3.0"
click = "^8.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
