[tool.poetry]
name = "skyhub"
version = "1.2.4"
description = ""
authors = ["Carmo-sousa <carmosousa20@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.9"
dynaconf = "^3.1.7"
aiohttp = "^3.7.4"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^21.9b0", allow-prereleases = true}
isort = {version = "^5.9.3", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
