[tool.poetry]
name = "omniclient"
version = "0.5.63"
description = ""
authors = ["Zafar Iqbal <ultrasine@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.11"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
